/**
 * ICD-10 mental health diagnosis codes (DSM-5 aligned, billable).
 * Source: SSIS ICD-10 Mental Health Billable Diagnosis Codes.
 * Truncated source descriptions have been expanded based on neighbouring codes.
 */
export type Icd10Code = { readonly code: string; readonly description: string };

export const ICD10_CODES: readonly Icd10Code[] = [
  { code: "F40.241", description: "Acrophobia" },
  { code: "F43.0", description: "Acute stress reaction" },
  { code: "F43.22", description: "Adjustment disorder with anxiety" },
  { code: "F43.21", description: "Adjustment disorder with depressed mood" },
  { code: "F43.24", description: "Adjustment disorder with disturbance of conduct" },
  { code: "F43.23", description: "Adjustment disorder with mixed anxiety and depressed mood" },
  { code: "F43.25", description: "Adjustment disorder with mixed disturbance of emotions and conduct" },
  { code: "F43.29", description: "Adjustment disorder with other symptoms" },
  { code: "F43.20", description: "Adjustment disorder, unspecified" },
  { code: "F51.02", description: "Adjustment insomnia" },
  { code: "F98.5", description: "Adult onset fluency disorder" },
  { code: "F40.01", description: "Agoraphobia with panic disorder" },
  { code: "F40.02", description: "Agoraphobia without panic disorder" },
  { code: "F40.00", description: "Agoraphobia, unspecified" },
  { code: "F10.180", description: "Alcohol abuse with alcohol-induced anxiety disorder" },
  { code: "F10.14", description: "Alcohol abuse with alcohol-induced mood disorder" },
  { code: "F10.150", description: "Alcohol abuse with alcohol-induced psychotic disorder with delusions" },
  { code: "F10.151", description: "Alcohol abuse with alcohol-induced psychotic disorder with hallucinations" },
  { code: "F10.159", description: "Alcohol abuse with alcohol-induced psychotic disorder, unspecified" },
  { code: "F10.181", description: "Alcohol abuse with alcohol-induced sexual dysfunction" },
  { code: "F10.182", description: "Alcohol abuse with alcohol-induced sleep disorder" },
  { code: "F10.121", description: "Alcohol abuse with intoxication delirium" },
  { code: "F10.188", description: "Alcohol abuse with other alcohol-induced disorder" },
  { code: "F10.19", description: "Alcohol abuse with unspecified alcohol-induced disorder" },
  { code: "F10.280", description: "Alcohol dependence with alcohol-induced anxiety disorder" },
  { code: "F10.24", description: "Alcohol dependence with alcohol-induced mood disorder" },
  { code: "F10.26", description: "Alcohol dependence with alcohol-induced persisting amnestic disorder" },
  { code: "F10.27", description: "Alcohol dependence with alcohol-induced persisting dementia" },
  { code: "F10.250", description: "Alcohol dependence with alcohol-induced psychotic disorder with delusions" },
  { code: "F10.251", description: "Alcohol dependence with alcohol-induced psychotic disorder with hallucinations" },
  { code: "F10.259", description: "Alcohol dependence with alcohol-induced psychotic disorder, unspecified" },
  { code: "F10.281", description: "Alcohol dependence with alcohol-induced sexual dysfunction" },
  { code: "F10.282", description: "Alcohol dependence with alcohol-induced sleep disorder" },
  { code: "F10.221", description: "Alcohol dependence with intoxication delirium" },
  { code: "F10.288", description: "Alcohol dependence with other alcohol-induced disorder" },
  { code: "F10.29", description: "Alcohol dependence with unspecified alcohol-induced disorder" },
  { code: "F10.231", description: "Alcohol dependence with withdrawal delirium" },
  { code: "F10.232", description: "Alcohol dependence with withdrawal with perceptual disturbance" },
  { code: "F10.239", description: "Alcohol dependence with withdrawal, unspecified" },
  { code: "F10.980", description: "Alcohol use, unspecified with alcohol-induced anxiety disorder" },
  { code: "F10.94", description: "Alcohol use, unspecified with alcohol-induced mood disorder" },
  { code: "F10.96", description: "Alcohol use, unspecified with alcohol-induced persisting amnestic disorder" },
  { code: "F10.97", description: "Alcohol use, unspecified with alcohol-induced persisting dementia" },
  { code: "F10.950", description: "Alcohol use, unspecified with alcohol-induced psychotic disorder with delusions" },
  { code: "F10.951", description: "Alcohol use, unspecified with alcohol-induced psychotic disorder with hallucinations" },
  { code: "F10.959", description: "Alcohol use, unspecified with alcohol-induced psychotic disorder, unspecified" },
  { code: "F10.981", description: "Alcohol use, unspecified with alcohol-induced sexual dysfunction" },
  { code: "F10.982", description: "Alcohol use, unspecified with alcohol-induced sleep disorder" },
  { code: "F10.921", description: "Alcohol use, unspecified with intoxication delirium" },
  { code: "F10.988", description: "Alcohol use, unspecified with other alcohol-induced disorder" },
  { code: "F04", description: "Amnestic disorder due to known physiological condition" },
  { code: "F40.290", description: "Androphobia" },
  { code: "F50.02", description: "Anorexia nervosa, binge eating/purging type" },
  { code: "F50.01", description: "Anorexia nervosa, restricting type" },
  { code: "F50.00", description: "Anorexia nervosa, unspecified" },
  { code: "F60.2", description: "Antisocial personality disorder" },
  { code: "F06.4", description: "Anxiety disorder due to known physiological condition" },
  { code: "F41.9", description: "Anxiety disorder, unspecified" },
  { code: "F40.210", description: "Arachnophobia" },
  { code: "F84.5", description: "Asperger's syndrome" },
  { code: "F90.2", description: "Attention-deficit hyperactivity disorder, combined type" },
  { code: "F90.8", description: "Attention-deficit hyperactivity disorder, other type" },
  { code: "F90.1", description: "Attention-deficit hyperactivity disorder, predominantly hyperactive type" },
  { code: "F90.0", description: "Attention-deficit hyperactivity disorder, predominantly inattentive type" },
  { code: "F90.9", description: "Attention-deficit hyperactivity disorder, unspecified type" },
  { code: "F84.0", description: "Autistic disorder" },
  { code: "F60.6", description: "Avoidant personality disorder" },
  { code: "F50.82", description: "Avoidant/restrictive food intake disorder" },
  { code: "F50.81", description: "Binge eating disorder" },
  { code: "F31.31", description: "Bipolar disorder, current episode depressed, mild" },
  { code: "F31.30", description: "Bipolar disorder, current episode depressed, mild or moderate severity, unspecified" },
  { code: "F31.32", description: "Bipolar disorder, current episode depressed, moderate" },
  { code: "F31.5", description: "Bipolar disorder, current episode depressed, severe, with psychotic features" },
  { code: "F31.4", description: "Bipolar disorder, current episode depressed, severe, without psychotic features" },
  { code: "F31.0", description: "Bipolar disorder, current episode hypomanic" },
  { code: "F31.2", description: "Bipolar disorder, current episode manic severe with psychotic features" },
  { code: "F31.11", description: "Bipolar disorder, current episode manic without psychotic features, mild" },
  { code: "F31.12", description: "Bipolar disorder, current episode manic without psychotic features, moderate" },
  { code: "F31.13", description: "Bipolar disorder, current episode manic without psychotic features, severe" },
  { code: "F31.10", description: "Bipolar disorder, current episode manic without psychotic features, unspecified" },
  { code: "F31.61", description: "Bipolar disorder, current episode mixed, mild" },
  { code: "F31.62", description: "Bipolar disorder, current episode mixed, moderate" },
  { code: "F31.64", description: "Bipolar disorder, current episode mixed, severe, with psychotic features" },
  { code: "F31.63", description: "Bipolar disorder, current episode mixed, severe, without psychotic features" },
  { code: "F31.60", description: "Bipolar disorder, current episode mixed, unspecified" },
  { code: "F31.70", description: "Bipolar disorder, currently in remission, most recent episode unspecified" },
  { code: "F31.76", description: "Bipolar disorder, in full remission, most recent episode depressed" },
  { code: "F31.72", description: "Bipolar disorder, in full remission, most recent episode hypomanic" },
  { code: "F31.74", description: "Bipolar disorder, in full remission, most recent episode manic" },
  { code: "F31.78", description: "Bipolar disorder, in full remission, most recent episode mixed" },
  { code: "F31.75", description: "Bipolar disorder, in partial remission, most recent episode depressed" },
  { code: "F31.71", description: "Bipolar disorder, in partial remission, most recent episode hypomanic" },
  { code: "F31.73", description: "Bipolar disorder, in partial remission, most recent episode manic" },
  { code: "F31.77", description: "Bipolar disorder, in partial remission, most recent episode mixed" },
  { code: "F31.9", description: "Bipolar disorder, unspecified" },
  { code: "F31.81", description: "Bipolar II disorder" },
  { code: "F45.22", description: "Body dysmorphic disorder" },
  { code: "F60.3", description: "Borderline personality disorder" },
  { code: "F23", description: "Brief psychotic disorder" },
  { code: "F50.2", description: "Bulimia nervosa" },
  { code: "F12.180", description: "Cannabis abuse with cannabis-induced anxiety disorder" },
  { code: "F12.121", description: "Cannabis abuse with intoxication delirium" },
  { code: "F12.122", description: "Cannabis abuse with intoxication with perceptual disturbance" },
  { code: "F12.188", description: "Cannabis abuse with other cannabis-induced disorder" },
  { code: "F12.150", description: "Cannabis abuse with psychotic disorder with delusions" },
  { code: "F12.151", description: "Cannabis abuse with psychotic disorder with hallucinations" },
  { code: "F12.159", description: "Cannabis abuse with psychotic disorder, unspecified" },
  { code: "F12.19", description: "Cannabis abuse with unspecified cannabis-induced disorder" },
  { code: "F12.280", description: "Cannabis dependence with cannabis-induced anxiety disorder" },
  { code: "F12.221", description: "Cannabis dependence with intoxication delirium" },
  { code: "F12.222", description: "Cannabis dependence with intoxication with perceptual disturbance" },
  { code: "F12.288", description: "Cannabis dependence with other cannabis-induced disorder" },
  { code: "F12.250", description: "Cannabis dependence with psychotic disorder with delusions" },
  { code: "F12.251", description: "Cannabis dependence with psychotic disorder with hallucinations" },
  { code: "F12.259", description: "Cannabis dependence with psychotic disorder, unspecified" },
  { code: "F12.29", description: "Cannabis dependence with unspecified cannabis-induced disorder" },
  { code: "F12.980", description: "Cannabis use, unspecified with anxiety disorder" },
  { code: "F12.921", description: "Cannabis use, unspecified with intoxication delirium" },
  { code: "F12.922", description: "Cannabis use, unspecified with intoxication with perceptual disturbance" },
  { code: "F12.988", description: "Cannabis use, unspecified with other cannabis-induced disorder" },
  { code: "F12.950", description: "Cannabis use, unspecified with psychotic disorder with delusions" },
  { code: "F12.951", description: "Cannabis use, unspecified with psychotic disorder with hallucinations" },
  { code: "F12.959", description: "Cannabis use, unspecified with psychotic disorder, unspecified" },
  { code: "F06.1", description: "Catatonic disorder due to known physiological condition" },
  { code: "F20.2", description: "Catatonic schizophrenia" },
  { code: "F93.9", description: "Childhood emotional disorder, unspecified" },
  { code: "F80.81", description: "Childhood onset fluency disorder" },
  { code: "F95.1", description: "Chronic motor or vocal tic disorder" },
  { code: "F40.240", description: "Claustrophobia" },
  { code: "F14.180", description: "Cocaine abuse with cocaine-induced anxiety disorder" },
  { code: "F14.14", description: "Cocaine abuse with cocaine-induced mood disorder" },
  { code: "F14.150", description: "Cocaine abuse with cocaine-induced psychotic disorder with delusions" },
  { code: "F14.151", description: "Cocaine abuse with cocaine-induced psychotic disorder with hallucinations" },
  { code: "F14.159", description: "Cocaine abuse with cocaine-induced psychotic disorder, unspecified" },
  { code: "F14.181", description: "Cocaine abuse with cocaine-induced sexual dysfunction" },
  { code: "F14.182", description: "Cocaine abuse with cocaine-induced sleep disorder" },
  { code: "F14.121", description: "Cocaine abuse with intoxication with delirium" },
  { code: "F14.122", description: "Cocaine abuse with intoxication with perceptual disturbance" },
  { code: "F14.188", description: "Cocaine abuse with other cocaine-induced disorder" },
  { code: "F14.19", description: "Cocaine abuse with unspecified cocaine-induced disorder" },
  { code: "F14.280", description: "Cocaine dependence with cocaine-induced anxiety disorder" },
  { code: "F14.24", description: "Cocaine dependence with cocaine-induced mood disorder" },
  { code: "F14.250", description: "Cocaine dependence with cocaine-induced psychotic disorder with delusions" },
  { code: "F14.251", description: "Cocaine dependence with cocaine-induced psychotic disorder with hallucinations" },
  { code: "F14.259", description: "Cocaine dependence with cocaine-induced psychotic disorder, unspecified" },
  { code: "F14.281", description: "Cocaine dependence with cocaine-induced sexual dysfunction" },
  { code: "F14.282", description: "Cocaine dependence with cocaine-induced sleep disorder" },
  { code: "F14.221", description: "Cocaine dependence with intoxication delirium" },
  { code: "F14.222", description: "Cocaine dependence with intoxication with perceptual disturbance" },
  { code: "F14.288", description: "Cocaine dependence with other cocaine-induced disorder" },
  { code: "F14.29", description: "Cocaine dependence with unspecified cocaine-induced disorder" },
  { code: "F14.980", description: "Cocaine use, unspecified with cocaine-induced anxiety disorder" },
  { code: "F14.94", description: "Cocaine use, unspecified with cocaine-induced mood disorder" },
  { code: "F14.950", description: "Cocaine use, unspecified with cocaine-induced psychotic disorder with delusions" },
  { code: "F14.951", description: "Cocaine use, unspecified with cocaine-induced psychotic disorder with hallucinations" },
  { code: "F14.959", description: "Cocaine use, unspecified with cocaine-induced psychotic disorder, unspecified" },
  { code: "F14.981", description: "Cocaine use, unspecified with cocaine-induced sexual dysfunction" },
  { code: "F14.982", description: "Cocaine use, unspecified with cocaine-induced sleep disorder" },
  { code: "F14.921", description: "Cocaine use, unspecified with intoxication delirium" },
  { code: "F14.922", description: "Cocaine use, unspecified with intoxication with perceptual disturbance" },
  { code: "F14.988", description: "Cocaine use, unspecified with other cocaine-induced disorder" },
  { code: "F91.0", description: "Conduct disorder confined to family context" },
  { code: "F91.2", description: "Conduct disorder, adolescent-onset type" },
  { code: "F91.1", description: "Conduct disorder, childhood-onset type" },
  { code: "F91.9", description: "Conduct disorder, unspecified" },
  { code: "F44.7", description: "Conversion disorder with mixed symptom presentation" },
  { code: "F44.4", description: "Conversion disorder with motor symptom or deficit" },
  { code: "F44.5", description: "Conversion disorder with seizures or convulsions" },
  { code: "F44.6", description: "Conversion disorder with sensory symptom or deficit" },
  { code: "F34.0", description: "Cyclothymic disorder" },
  { code: "F05", description: "Delirium due to known physiological condition" },
  { code: "F22", description: "Delusional disorders" },
  { code: "F02.81", description: "Dementia in other diseases classified elsewhere with behavioral disturbance" },
  { code: "F02.80", description: "Dementia in other diseases classified elsewhere without behavioral disturbance" },
  { code: "F60.7", description: "Dependent personality disorder" },
  { code: "F48.1", description: "Depersonalization-derealization syndrome" },
  { code: "F94.2", description: "Disinhibited attachment disorder of childhood" },
  { code: "F20.1", description: "Disorganized schizophrenia" },
  { code: "F34.81", description: "Disruptive mood dysregulation disorder" },
  { code: "F44.0", description: "Dissociative amnesia" },
  { code: "F44.9", description: "Dissociative and conversion disorder, unspecified" },
  { code: "F44.1", description: "Dissociative fugue" },
  { code: "F44.81", description: "Dissociative identity disorder" },
  { code: "F44.2", description: "Dissociative stupor" },
  { code: "F52.6", description: "Dyspareunia not due to a substance or known physiological condition" },
  { code: "F34.1", description: "Dysthymic disorder" },
  { code: "F50.9", description: "Eating disorder, unspecified" },
  { code: "F98.1", description: "Encopresis not due to a substance or known physiological condition" },
  { code: "F98.0", description: "Enuresis not due to a substance or known physiological condition" },
  { code: "F42.4", description: "Excoriation (skin-picking) disorder" },
  { code: "F65.2", description: "Exhibitionism" },
  { code: "F68.13", description: "Factitious disorder with combined psychological and physical signs and symptoms" },
  { code: "F68.12", description: "Factitious disorder with predominantly physical signs and symptoms" },
  { code: "F68.11", description: "Factitious disorder with predominantly psychological signs and symptoms" },
  { code: "F68.10", description: "Factitious disorder, unspecified" },
  { code: "F40.230", description: "Fear of blood" },
  { code: "F40.242", description: "Fear of bridges" },
  { code: "F40.243", description: "Fear of flying" },
  { code: "F40.231", description: "Fear of injections and transfusions" },
  { code: "F40.233", description: "Fear of injury" },
  { code: "F40.232", description: "Fear of other medical care" },
  { code: "F40.220", description: "Fear of thunderstorms" },
  { code: "F52.31", description: "Female orgasmic disorder" },
  { code: "F52.22", description: "Female sexual arousal disorder" },
  { code: "F65.0", description: "Fetishism" },
  { code: "F65.81", description: "Frotteurism" },
  { code: "F64.1", description: "Gender identity disorder in adolescence and adulthood" },
  { code: "F64.2", description: "Gender identity disorder of childhood" },
  { code: "F64.9", description: "Gender identity disorder, unspecified" },
  { code: "F41.1", description: "Generalized anxiety disorder" },
  { code: "F40.291", description: "Gynephobia" },
  { code: "F16.183", description: "Hallucinogen abuse with hallucinogen persisting perception disorder (flashbacks)" },
  { code: "F16.180", description: "Hallucinogen abuse with hallucinogen-induced anxiety disorder" },
  { code: "F16.14", description: "Hallucinogen abuse with hallucinogen-induced mood disorder" },
  { code: "F16.150", description: "Hallucinogen abuse with hallucinogen-induced psychotic disorder with delusions" },
  { code: "F16.151", description: "Hallucinogen abuse with hallucinogen-induced psychotic disorder with hallucinations" },
  { code: "F16.159", description: "Hallucinogen abuse with hallucinogen-induced psychotic disorder, unspecified" },
  { code: "F16.121", description: "Hallucinogen abuse with intoxication with delirium" },
  { code: "F16.122", description: "Hallucinogen abuse with intoxication with perceptual disturbance" },
  { code: "F16.188", description: "Hallucinogen abuse with other hallucinogen-induced disorder" },
  { code: "F16.19", description: "Hallucinogen abuse with unspecified hallucinogen-induced disorder" },
  { code: "F16.283", description: "Hallucinogen dependence with hallucinogen persisting perception disorder (flashbacks)" },
  { code: "F16.280", description: "Hallucinogen dependence with hallucinogen-induced anxiety disorder" },
  { code: "F16.24", description: "Hallucinogen dependence with hallucinogen-induced mood disorder" },
  { code: "F16.250", description: "Hallucinogen dependence with hallucinogen-induced psychotic disorder with delusions" },
  { code: "F16.251", description: "Hallucinogen dependence with hallucinogen-induced psychotic disorder with hallucinations" },
  { code: "F16.259", description: "Hallucinogen dependence with hallucinogen-induced psychotic disorder, unspecified" },
  { code: "F16.221", description: "Hallucinogen dependence with intoxication with delirium" },
  { code: "F16.288", description: "Hallucinogen dependence with other hallucinogen-induced disorder" },
  { code: "F16.29", description: "Hallucinogen dependence with unspecified hallucinogen-induced disorder" },
  { code: "F16.983", description: "Hallucinogen use, unspecified with hallucinogen persisting perception disorder (flashbacks)" },
  { code: "F16.980", description: "Hallucinogen use, unspecified with hallucinogen-induced anxiety disorder" },
  { code: "F16.94", description: "Hallucinogen use, unspecified with hallucinogen-induced mood disorder" },
  { code: "F16.950", description: "Hallucinogen use, unspecified with hallucinogen-induced psychotic disorder with delusions" },
  { code: "F16.951", description: "Hallucinogen use, unspecified with hallucinogen-induced psychotic disorder with hallucinations" },
  { code: "F16.959", description: "Hallucinogen use, unspecified with hallucinogen-induced psychotic disorder, unspecified" },
  { code: "F16.921", description: "Hallucinogen use, unspecified with intoxication with delirium" },
  { code: "F16.988", description: "Hallucinogen use, unspecified with other hallucinogen-induced disorder" },
  { code: "F60.4", description: "Histrionic personality disorder" },
  { code: "F42.3", description: "Hoarding disorder" },
  { code: "F52.0", description: "Hypoactive sexual desire disorder" },
  { code: "F45.20", description: "Hypochondriacal disorder, unspecified" },
  { code: "F45.21", description: "Hypochondriasis" },
  { code: "F63.9", description: "Impulse disorder, unspecified" },
  { code: "F18.180", description: "Inhalant abuse with inhalant-induced anxiety disorder" },
  { code: "F18.17", description: "Inhalant abuse with inhalant-induced dementia" },
  { code: "F18.14", description: "Inhalant abuse with inhalant-induced mood disorder" },
  { code: "F18.150", description: "Inhalant abuse with inhalant-induced psychotic disorder with delusions" },
  { code: "F18.151", description: "Inhalant abuse with inhalant-induced psychotic disorder with hallucinations" },
  { code: "F18.159", description: "Inhalant abuse with inhalant-induced psychotic disorder, unspecified" },
  { code: "F18.121", description: "Inhalant abuse with intoxication delirium" },
  { code: "F18.188", description: "Inhalant abuse with other inhalant-induced disorder" },
  { code: "F18.19", description: "Inhalant abuse with unspecified inhalant-induced disorder" },
  { code: "F18.280", description: "Inhalant dependence with inhalant-induced anxiety disorder" },
  { code: "F18.27", description: "Inhalant dependence with inhalant-induced dementia" },
  { code: "F18.24", description: "Inhalant dependence with inhalant-induced mood disorder" },
  { code: "F18.250", description: "Inhalant dependence with inhalant-induced psychotic disorder with delusions" },
  { code: "F18.251", description: "Inhalant dependence with inhalant-induced psychotic disorder with hallucinations" },
  { code: "F18.259", description: "Inhalant dependence with inhalant-induced psychotic disorder, unspecified" },
  { code: "F18.221", description: "Inhalant dependence with intoxication delirium" },
  { code: "F18.980", description: "Inhalant use, unspecified with inhalant-induced anxiety disorder" },
  { code: "F18.94", description: "Inhalant use, unspecified with inhalant-induced mood disorder" },
  { code: "F18.97", description: "Inhalant use, unspecified with inhalant-induced persisting dementia" },
  { code: "F18.950", description: "Inhalant use, unspecified with inhalant-induced psychotic disorder with delusions" },
  { code: "F18.951", description: "Inhalant use, unspecified with inhalant-induced psychotic disorder with hallucinations" },
  { code: "F18.959", description: "Inhalant use, unspecified with inhalant-induced psychotic disorder, unspecified" },
  { code: "F18.921", description: "Inhalant use, unspecified with intoxication with delirium" },
  { code: "F51.05", description: "Insomnia due to other mental disorder" },
  { code: "F51.12", description: "Insufficient sleep syndrome" },
  { code: "F63.81", description: "Intermittent explosive disorder" },
  { code: "F63.2", description: "Kleptomania" },
  { code: "F33.2", description: "Major depressive disorder, recurrent severe without psychotic features" },
  { code: "F33.42", description: "Major depressive disorder, recurrent, in full remission" },
  { code: "F33.41", description: "Major depressive disorder, recurrent, in partial remission" },
  { code: "F33.40", description: "Major depressive disorder, recurrent, in remission, unspecified" },
  { code: "F33.0", description: "Major depressive disorder, recurrent, mild" },
  { code: "F33.1", description: "Major depressive disorder, recurrent, moderate" },
  { code: "F33.3", description: "Major depressive disorder, recurrent, severe with psychotic symptoms" },
  { code: "F33.9", description: "Major depressive disorder, recurrent, unspecified" },
  { code: "F32.5", description: "Major depressive disorder, single episode, in full remission" },
  { code: "F32.4", description: "Major depressive disorder, single episode, in partial remission" },
  { code: "F32.0", description: "Major depressive disorder, single episode, mild" },
  { code: "F32.1", description: "Major depressive disorder, single episode, moderate" },
  { code: "F32.3", description: "Major depressive disorder, single episode, severe with psychotic features" },
  { code: "F32.2", description: "Major depressive disorder, single episode, severe without psychotic features" },
  { code: "F32.9", description: "Major depressive disorder, single episode, unspecified" },
  { code: "F52.21", description: "Male erectile disorder" },
  { code: "F52.32", description: "Male orgasmic disorder" },
  { code: "F30.4", description: "Manic episode in full remission" },
  { code: "F30.3", description: "Manic episode in partial remission" },
  { code: "F30.11", description: "Manic episode without psychotic symptoms, mild" },
  { code: "F30.12", description: "Manic episode without psychotic symptoms, moderate" },
  { code: "F30.10", description: "Manic episode without psychotic symptoms, unspecified" },
  { code: "F30.2", description: "Manic episode, severe with psychotic symptoms" },
  { code: "F30.13", description: "Manic episode, severe, without psychotic symptoms" },
  { code: "F30.9", description: "Manic episode, unspecified" },
  { code: "F42.2", description: "Mixed obsessional thoughts and acts" },
  { code: "F06.31", description: "Mood disorder due to known physiological condition with depressive features" },
  { code: "F06.32", description: "Mood disorder due to known physiological condition with major depressive-like episode" },
  { code: "F06.33", description: "Mood disorder due to known physiological condition with manic features" },
  { code: "F06.34", description: "Mood disorder due to known physiological condition with mixed features" },
  { code: "F06.30", description: "Mood disorder due to known physiological condition, unspecified" },
  { code: "F60.81", description: "Narcissistic personality disorder" },
  { code: "F51.5", description: "Nightmare disorder" },
  { code: "F48.9", description: "Nonpsychotic mental disorder, unspecified" },
  { code: "F42", description: "Obsessive-compulsive disorder" },
  { code: "F60.5", description: "Obsessive-compulsive personality disorder" },
  { code: "F11.121", description: "Opioid abuse with intoxication delirium" },
  { code: "F11.122", description: "Opioid abuse with intoxication with perceptual disturbance" },
  { code: "F11.14", description: "Opioid abuse with opioid-induced mood disorder" },
  { code: "F11.150", description: "Opioid abuse with opioid-induced psychotic disorder with delusions" },
  { code: "F11.151", description: "Opioid abuse with opioid-induced psychotic disorder with hallucinations" },
  { code: "F11.159", description: "Opioid abuse with opioid-induced psychotic disorder, unspecified" },
  { code: "F11.181", description: "Opioid abuse with opioid-induced sexual dysfunction" },
  { code: "F11.182", description: "Opioid abuse with opioid-induced sleep disorder" },
  { code: "F11.188", description: "Opioid abuse with other opioid-induced disorder" },
  { code: "F11.19", description: "Opioid abuse with unspecified opioid-induced disorder" },
  { code: "F11.221", description: "Opioid dependence with intoxication delirium" },
  { code: "F11.24", description: "Opioid dependence with opioid-induced mood disorder" },
  { code: "F11.250", description: "Opioid dependence with opioid-induced psychotic disorder with delusions" },
  { code: "F11.251", description: "Opioid dependence with opioid-induced psychotic disorder with hallucinations" },
  { code: "F11.259", description: "Opioid dependence with opioid-induced psychotic disorder, unspecified" },
  { code: "F11.281", description: "Opioid dependence with opioid-induced sexual dysfunction" },
  { code: "F11.282", description: "Opioid dependence with opioid-induced sleep disorder" },
  { code: "F11.288", description: "Opioid dependence with other opioid-induced disorder" },
  { code: "F11.29", description: "Opioid dependence with unspecified opioid-induced disorder" },
  { code: "F11.921", description: "Opioid use, unspecified with intoxication delirium" },
  { code: "F11.922", description: "Opioid use, unspecified with intoxication with perceptual disturbance" },
  { code: "F11.94", description: "Opioid use, unspecified with opioid-induced mood disorder" },
  { code: "F11.950", description: "Opioid use, unspecified with opioid-induced psychotic disorder with delusions" },
  { code: "F11.951", description: "Opioid use, unspecified with opioid-induced psychotic disorder with hallucinations" },
  { code: "F11.959", description: "Opioid use, unspecified with opioid-induced psychotic disorder, unspecified" },
  { code: "F11.981", description: "Opioid use, unspecified with opioid-induced sexual dysfunction" },
  { code: "F11.982", description: "Opioid use, unspecified with opioid-induced sleep disorder" },
  { code: "F11.988", description: "Opioid use, unspecified with other opioid-induced disorder" },
  { code: "F91.3", description: "Oppositional defiant disorder" },
  { code: "F40.218", description: "Other animal type phobia" },
  { code: "F31.89", description: "Other bipolar disorder" },
  { code: "F84.3", description: "Other childhood disintegrative disorder" },
  { code: "F94.8", description: "Other childhood disorders of social functioning" },
  { code: "F93.8", description: "Other childhood emotional disorders" },
  { code: "F91.8", description: "Other conduct disorders" },
  { code: "F32.8", description: "Other depressive episodes" },
  { code: "F80.89", description: "Other developmental disorders of speech and language" },
  { code: "F88", description: "Other disorders of psychological development" },
  { code: "F50.8", description: "Other eating disorders" },
  { code: "F98.29", description: "Other feeding disorders of infancy and early childhood" },
  { code: "F64.8", description: "Other gender identity disorders" },
  { code: "F45.29", description: "Other hypochondriacal disorders" },
  { code: "F63.8", description: "Other impulse disorders" },
  { code: "F51.09", description: "Other insomnia not due to a substance or known physiological condition" },
  { code: "F30.8", description: "Other manic episodes" },
  { code: "F41.3", description: "Other mixed anxiety disorders" },
  { code: "F40.228", description: "Other natural environment type phobia" },
  { code: "F42.8", description: "Other obsessive compulsive disorder" },
  { code: "F65.89", description: "Other paraphilias" },
  { code: "F34.8", description: "Other persistent mood (affective) disorders" },
  { code: "F07.89", description: "Other personality and behavioral disorders due to known physiological condition" },
  { code: "F84.8", description: "Other pervasive developmental disorders" },
  { code: "F40.8", description: "Other phobic anxiety disorders" },
  { code: "F19.121", description: "Other psychoactive substance abuse with intoxication delirium" },
  { code: "F19.122", description: "Other psychoactive substance abuse with intoxication with perceptual disturbances" },
  { code: "F19.188", description: "Other psychoactive substance abuse with other psychoactive substance-induced disorder" },
  { code: "F19.180", description: "Other psychoactive substance abuse with psychoactive substance-induced anxiety disorder" },
  { code: "F19.14", description: "Other psychoactive substance abuse with psychoactive substance-induced mood disorder" },
  { code: "F19.16", description: "Other psychoactive substance abuse with psychoactive substance-induced persisting amnestic disorder" },
  { code: "F19.17", description: "Other psychoactive substance abuse with psychoactive substance-induced persisting dementia" },
  { code: "F19.150", description: "Other psychoactive substance abuse with psychoactive substance-induced psychotic disorder with delusions" },
  { code: "F19.151", description: "Other psychoactive substance abuse with psychoactive substance-induced psychotic disorder with hallucinations" },
  { code: "F19.159", description: "Other psychoactive substance abuse with psychoactive substance-induced psychotic disorder, unspecified" },
  { code: "F19.181", description: "Other psychoactive substance abuse with psychoactive substance-induced sexual dysfunction" },
  { code: "F19.182", description: "Other psychoactive substance abuse with psychoactive substance-induced sleep disorder" },
  { code: "F19.19", description: "Other psychoactive substance abuse with unspecified psychoactive substance-induced disorder" },
  { code: "F19.221", description: "Other psychoactive substance dependence with intoxication delirium" },
  { code: "F19.222", description: "Other psychoactive substance dependence with intoxication with perceptual disturbance" },
  { code: "F19.288", description: "Other psychoactive substance dependence with other psychoactive substance-induced disorder" },
  { code: "F19.280", description: "Other psychoactive substance dependence with psychoactive substance-induced anxiety disorder" },
  { code: "F19.24", description: "Other psychoactive substance dependence with psychoactive substance-induced mood disorder" },
  { code: "F19.26", description: "Other psychoactive substance dependence with psychoactive substance-induced persisting amnestic disorder" },
  { code: "F19.27", description: "Other psychoactive substance dependence with psychoactive substance-induced persisting dementia" },
  { code: "F19.250", description: "Other psychoactive substance dependence with psychoactive substance-induced psychotic disorder with delusions" },
  { code: "F19.251", description: "Other psychoactive substance dependence with psychoactive substance-induced psychotic disorder with hallucinations" },
  { code: "F19.259", description: "Other psychoactive substance dependence with psychoactive substance-induced psychotic disorder, unspecified" },
  { code: "F19.281", description: "Other psychoactive substance dependence with psychoactive substance-induced sexual dysfunction" },
  { code: "F19.282", description: "Other psychoactive substance dependence with psychoactive substance-induced sleep disorder" },
  { code: "F19.29", description: "Other psychoactive substance dependence with unspecified psychoactive substance-induced disorder" },
  { code: "F19.231", description: "Other psychoactive substance dependence with withdrawal delirium" },
  { code: "F19.232", description: "Other psychoactive substance dependence with withdrawal with perceptual disturbance" },
  { code: "F19.239", description: "Other psychoactive substance dependence with withdrawal, unspecified" },
  { code: "F19.921", description: "Other psychoactive substance use, unspecified with intoxication with delirium" },
  { code: "F19.922", description: "Other psychoactive substance use, unspecified with intoxication with perceptual disturbance" },
  { code: "F19.988", description: "Other psychoactive substance use, unspecified with other psychoactive substance-induced disorder" },
  { code: "F19.980", description: "Other psychoactive substance use, unspecified with psychoactive substance-induced anxiety disorder" },
  { code: "F19.94", description: "Other psychoactive substance use, unspecified with psychoactive substance-induced mood disorder" },
  { code: "F19.96", description: "Other psychoactive substance use, unspecified with psychoactive substance-induced persisting amnestic disorder" },
  { code: "F19.97", description: "Other psychoactive substance use, unspecified with psychoactive substance-induced persisting dementia" },
  { code: "F19.950", description: "Other psychoactive substance use, unspecified with psychoactive substance-induced psychotic disorder with delusions" },
  { code: "F19.951", description: "Other psychoactive substance use, unspecified with psychoactive substance-induced psychotic disorder with hallucinations" },
  { code: "F19.959", description: "Other psychoactive substance use, unspecified with psychoactive substance-induced psychotic disorder, unspecified" },
  { code: "F19.981", description: "Other psychoactive substance use, unspecified with psychoactive substance-induced sexual dysfunction" },
  { code: "F19.982", description: "Other psychoactive substance use, unspecified with psychoactive substance-induced sleep disorder" },
  { code: "F19.931", description: "Other psychoactive substance use, unspecified with withdrawal delirium" },
  { code: "F19.932", description: "Other psychoactive substance use, unspecified with withdrawal with perceptual disturbance" },
  { code: "F28", description: "Other psychotic disorder not due to a substance or known physiological condition" },
  { code: "F43.8", description: "Other reactions to severe stress" },
  { code: "F33.8", description: "Other recurrent depressive disorders" },
  { code: "F25.8", description: "Other schizoaffective disorders" },
  { code: "F20.89", description: "Other schizophrenia" },
  { code: "F66", description: "Other sexual disorders" },
  { code: "F52.8", description: "Other sexual dysfunction not due to a substance or known physiological condition" },
  { code: "F40.248", description: "Other situational type phobia" },
  { code: "F51.8", description: "Other sleep disorders not due to a substance or known physiological condition" },
  { code: "F45.8", description: "Other somatoform disorders" },
  { code: "F60.89", description: "Other specific personality disorders" },
  { code: "F41.8", description: "Other specified anxiety disorders" },
  { code: "F98.8", description: "Other specified behavioral and emotional disorders with onset usually occurring in childhood and adolescence" },
  { code: "F32.89", description: "Other specified depressive episodes" },
  { code: "F68.8", description: "Other specified disorders of adult personality and behavior" },
  { code: "F50.89", description: "Other specified eating disorder" },
  { code: "F06.8", description: "Other specified mental disorders due to known physiological condition" },
  { code: "F34.89", description: "Other specified persistent mood disorders" },
  { code: "F40.298", description: "Other specified phobia" },
  { code: "F15.121", description: "Other stimulant abuse with intoxication delirium" },
  { code: "F15.122", description: "Other stimulant abuse with intoxication with perceptual disturbance" },
  { code: "F15.188", description: "Other stimulant abuse with other stimulant-induced disorder" },
  { code: "F15.180", description: "Other stimulant abuse with stimulant-induced anxiety disorder" },
  { code: "F15.14", description: "Other stimulant abuse with stimulant-induced mood disorder" },
  { code: "F15.150", description: "Other stimulant abuse with stimulant-induced psychotic disorder with delusions" },
  { code: "F15.151", description: "Other stimulant abuse with stimulant-induced psychotic disorder with hallucinations" },
  { code: "F15.159", description: "Other stimulant abuse with stimulant-induced psychotic disorder, unspecified" },
  { code: "F15.181", description: "Other stimulant abuse with stimulant-induced sexual dysfunction" },
  { code: "F15.182", description: "Other stimulant abuse with stimulant-induced sleep disorder" },
  { code: "F15.19", description: "Other stimulant abuse with unspecified stimulant-induced disorder" },
  { code: "F15.221", description: "Other stimulant dependence with intoxication delirium" },
  { code: "F15.222", description: "Other stimulant dependence with intoxication with perceptual disturbance" },
  { code: "F15.288", description: "Other stimulant dependence with other stimulant-induced disorder" },
  { code: "F15.280", description: "Other stimulant dependence with stimulant-induced anxiety disorder" },
  { code: "F15.24", description: "Other stimulant dependence with stimulant-induced mood disorder" },
  { code: "F15.250", description: "Other stimulant dependence with stimulant-induced psychotic disorder with delusions" },
  { code: "F15.251", description: "Other stimulant dependence with stimulant-induced psychotic disorder with hallucinations" },
  { code: "F15.259", description: "Other stimulant dependence with stimulant-induced psychotic disorder, unspecified" },
  { code: "F15.281", description: "Other stimulant dependence with stimulant-induced sexual dysfunction" },
  { code: "F15.282", description: "Other stimulant dependence with stimulant-induced sleep disorder" },
  { code: "F15.29", description: "Other stimulant dependence with unspecified stimulant-induced disorder" },
  { code: "F15.921", description: "Other stimulant use, unspecified with intoxication delirium" },
  { code: "F15.922", description: "Other stimulant use, unspecified with intoxication with perceptual disturbance" },
  { code: "F15.988", description: "Other stimulant use, unspecified with other stimulant-induced disorder" },
  { code: "F15.980", description: "Other stimulant use, unspecified with stimulant-induced anxiety disorder" },
  { code: "F15.94", description: "Other stimulant use, unspecified with stimulant-induced mood disorder" },
  { code: "F15.950", description: "Other stimulant use, unspecified with stimulant-induced psychotic disorder with delusions" },
  { code: "F15.951", description: "Other stimulant use, unspecified with stimulant-induced psychotic disorder with hallucinations" },
  { code: "F15.959", description: "Other stimulant use, unspecified with stimulant-induced psychotic disorder, unspecified" },
  { code: "F15.981", description: "Other stimulant use, unspecified with stimulant-induced sexual dysfunction" },
  { code: "F15.982", description: "Other stimulant use, unspecified with stimulant-induced sleep disorder" },
  { code: "F95.8", description: "Other tic disorders" },
  { code: "F45.41", description: "Pain disorder exclusively related to psychological factors" },
  { code: "F45.42", description: "Pain disorder with related psychological factors" },
  { code: "F41.0", description: "Panic Disorder (episodic paroxysmal anxiety)" },
  { code: "F51.03", description: "Paradoxical insomnia" },
  { code: "F60.0", description: "Paranoid personality disorder" },
  { code: "F20.0", description: "Paranoid schizophrenia" },
  { code: "F65.9", description: "Paraphilia, unspecified" },
  { code: "F63.0", description: "Pathological gambling" },
  { code: "F65.4", description: "Pedophilia" },
  { code: "F34.9", description: "Persistent mood (affective) disorder, unspecified" },
  { code: "F07.0", description: "Personality change due to known physiological condition" },
  { code: "F60.9", description: "Personality disorder, unspecified" },
  { code: "F84.9", description: "Pervasive developmental disorder, unspecified" },
  { code: "F40.9", description: "Phobic anxiety disorder, unspecified" },
  { code: "F98.3", description: "Pica of infancy and childhood" },
  { code: "F43.11", description: "Post-traumatic stress disorder, acute" },
  { code: "F43.12", description: "Post-traumatic stress disorder, chronic" },
  { code: "F43.10", description: "Post-traumatic stress disorder, unspecified" },
  { code: "F07.81", description: "Postconcussional syndrome" },
  { code: "F52.4", description: "Premature ejaculation" },
  { code: "F32.81", description: "Premenstrual dysphoric disorder" },
  { code: "F51.11", description: "Primary hypersomnia" },
  { code: "F51.01", description: "Primary insomnia" },
  { code: "F48.2", description: "Pseudobulbar affect" },
  { code: "F06.2", description: "Psychotic disorder with delusions due to known physiological condition" },
  { code: "F06.0", description: "Psychotic disorder with hallucinations due to known physiological condition" },
  { code: "F53", description: "Puerperal psychosis" },
  { code: "F63.1", description: "Pyromania" },
  { code: "F43.9", description: "Reaction to severe stress, unspecified" },
  { code: "F94.1", description: "Reactive attachment disorder of childhood" },
  { code: "F20.5", description: "Residual schizophrenia" },
  { code: "F98.21", description: "Rumination disorder of infancy" },
  { code: "F65.50", description: "Sadomasochism, unspecified" },
  { code: "F25.0", description: "Schizoaffective disorder, bipolar type" },
  { code: "F25.1", description: "Schizoaffective disorder, depressive type" },
  { code: "F25.9", description: "Schizoaffective disorder, unspecified" },
  { code: "F60.1", description: "Schizoid personality disorder" },
  { code: "F20.9", description: "Schizophrenia, unspecified" },
  { code: "F20.81", description: "Schizophreniform disorder" },
  { code: "F21", description: "Schizotypal disorder" },
  { code: "F13.121", description: "Sedative, hypnotic or anxiolytic abuse with intoxication delirium" },
  { code: "F13.188", description: "Sedative, hypnotic or anxiolytic abuse with other sedative, hypnotic or anxiolytic-induced disorder" },
  { code: "F13.180", description: "Sedative, hypnotic or anxiolytic abuse with sedative, hypnotic or anxiolytic-induced anxiety disorder" },
  { code: "F13.14", description: "Sedative, hypnotic or anxiolytic abuse with sedative, hypnotic or anxiolytic-induced mood disorder" },
  { code: "F13.150", description: "Sedative, hypnotic or anxiolytic abuse with sedative, hypnotic or anxiolytic-induced psychotic disorder with delusions" },
  { code: "F13.151", description: "Sedative, hypnotic or anxiolytic abuse with sedative, hypnotic or anxiolytic-induced psychotic disorder with hallucinations" },
  { code: "F13.159", description: "Sedative, hypnotic or anxiolytic abuse with sedative, hypnotic or anxiolytic-induced psychotic disorder, unspecified" },
  { code: "F13.181", description: "Sedative, hypnotic or anxiolytic abuse with sedative, hypnotic or anxiolytic-induced sexual dysfunction" },
  { code: "F13.182", description: "Sedative, hypnotic or anxiolytic abuse with sedative, hypnotic or anxiolytic-induced sleep disorder" },
  { code: "F13.19", description: "Sedative, hypnotic or anxiolytic abuse with unspecified sedative, hypnotic or anxiolytic-induced disorder" },
  { code: "F13.221", description: "Sedative, hypnotic or anxiolytic dependence with intoxication delirium" },
  { code: "F13.288", description: "Sedative, hypnotic or anxiolytic dependence with other sedative, hypnotic or anxiolytic-induced disorder" },
  { code: "F13.280", description: "Sedative, hypnotic or anxiolytic dependence with sedative, hypnotic or anxiolytic-induced anxiety disorder" },
  { code: "F13.24", description: "Sedative, hypnotic or anxiolytic dependence with sedative, hypnotic or anxiolytic-induced mood disorder" },
  { code: "F13.26", description: "Sedative, hypnotic or anxiolytic dependence with sedative, hypnotic or anxiolytic-induced persisting amnestic disorder" },
  { code: "F13.27", description: "Sedative, hypnotic or anxiolytic dependence with sedative, hypnotic or anxiolytic-induced persisting dementia" },
  { code: "F13.250", description: "Sedative, hypnotic or anxiolytic dependence with sedative, hypnotic or anxiolytic-induced psychotic disorder with delusions" },
  { code: "F13.251", description: "Sedative, hypnotic or anxiolytic dependence with sedative, hypnotic or anxiolytic-induced psychotic disorder with hallucinations" },
  { code: "F13.259", description: "Sedative, hypnotic or anxiolytic dependence with sedative, hypnotic or anxiolytic-induced psychotic disorder, unspecified" },
  { code: "F13.281", description: "Sedative, hypnotic or anxiolytic dependence with sedative, hypnotic or anxiolytic-induced sexual dysfunction" },
  { code: "F13.282", description: "Sedative, hypnotic or anxiolytic dependence with sedative, hypnotic or anxiolytic-induced sleep disorder" },
  { code: "F13.29", description: "Sedative, hypnotic or anxiolytic dependence with unspecified sedative, hypnotic or anxiolytic-induced disorder" },
  { code: "F13.231", description: "Sedative, hypnotic or anxiolytic dependence with withdrawal delirium" },
  { code: "F13.232", description: "Sedative, hypnotic or anxiolytic dependence with withdrawal with perceptual disturbance" },
  { code: "F13.239", description: "Sedative, hypnotic or anxiolytic dependence with withdrawal, unspecified" },
  { code: "F13.921", description: "Sedative, hypnotic or anxiolytic use, unspecified with intoxication delirium" },
  { code: "F13.988", description: "Sedative, hypnotic or anxiolytic use, unspecified with other sedative, hypnotic or anxiolytic-induced disorder" },
  { code: "F13.980", description: "Sedative, hypnotic or anxiolytic use, unspecified with sedative, hypnotic or anxiolytic-induced anxiety disorder" },
  { code: "F13.94", description: "Sedative, hypnotic or anxiolytic use, unspecified with sedative, hypnotic or anxiolytic-induced mood disorder" },
  { code: "F13.96", description: "Sedative, hypnotic or anxiolytic use, unspecified with sedative, hypnotic or anxiolytic-induced persisting amnestic disorder" },
  { code: "F13.97", description: "Sedative, hypnotic or anxiolytic use, unspecified with sedative, hypnotic or anxiolytic-induced persisting dementia" },
  { code: "F13.950", description: "Sedative, hypnotic or anxiolytic use, unspecified with sedative, hypnotic or anxiolytic-induced psychotic disorder with delusions" },
  { code: "F13.951", description: "Sedative, hypnotic or anxiolytic use, unspecified with sedative, hypnotic or anxiolytic-induced psychotic disorder with hallucinations" },
  { code: "F13.959", description: "Sedative, hypnotic or anxiolytic use, unspecified with sedative, hypnotic or anxiolytic-induced psychotic disorder, unspecified" },
  { code: "F13.981", description: "Sedative, hypnotic or anxiolytic use, unspecified with sedative, hypnotic or anxiolytic-induced sexual dysfunction" },
  { code: "F13.982", description: "Sedative, hypnotic or anxiolytic use, unspecified with sedative, hypnotic or anxiolytic-induced sleep disorder" },
  { code: "F13.931", description: "Sedative, hypnotic or anxiolytic use, unspecified with withdrawal delirium" },
  { code: "F13.932", description: "Sedative, hypnotic or anxiolytic use, unspecified with withdrawal with perceptual disturbances" },
  { code: "F94.0", description: "Selective mutism" },
  { code: "F93.0", description: "Separation anxiety disorder of childhood" },
  { code: "F52.1", description: "Sexual aversion disorder" },
  { code: "F65.51", description: "Sexual masochism" },
  { code: "F65.52", description: "Sexual sadism" },
  { code: "F24", description: "Shared psychotic disorder" },
  { code: "F51.9", description: "Sleep disorder not due to a substance or known physiological condition, unspecified" },
  { code: "F51.4", description: "Sleep terrors (night terrors)" },
  { code: "F51.3", description: "Sleepwalking (somnambulism)" },
  { code: "F40.11", description: "Social phobia, generalized" },
  { code: "F40.10", description: "Social phobia, unspecified" },
  { code: "F80.82", description: "Social pragmatic communication disorder" },
  { code: "F45.0", description: "Somatization disorder" },
  { code: "F45.9", description: "Somatoform disorder, unspecified" },
  { code: "R45.7", description: "State of emotional shock and stress, unspecified" },
  { code: "F98.4", description: "Stereotyped movement disorders" },
  { code: "F95.9", description: "Tic disorder, unspecified" },
  { code: "F95.2", description: "Tourette's disorder" },
  { code: "F95.0", description: "Transient tic disorder" },
  { code: "F64.0", description: "Transsexualism" },
  { code: "F65.1", description: "Transvestic fetishism" },
  { code: "F63.3", description: "Trichotillomania" },
  { code: "F20.3", description: "Undifferentiated schizophrenia" },
  { code: "F45.1", description: "Undifferentiated somatoform disorder" },
  { code: "F98.9", description: "Unspecified behavioral and emotional disorders with onset usually occurring in childhood and adolescence" },
  { code: "F59", description: "Unspecified behavioral syndromes associated with physiological disturbances and physical factors" },
  { code: "F03.91", description: "Unspecified dementia with behavioral disturbance" },
  { code: "F03.90", description: "Unspecified dementia without behavioral disturbance" },
  { code: "F89", description: "Unspecified disorder of psychological development" },
  { code: "F09", description: "Unspecified mental disorder due to known physiological condition" },
  { code: "F39", description: "Unspecified mood (affective) disorder" },
  { code: "F07.9", description: "Unspecified personality and behavioral disorder due to known physiological condition" },
  { code: "F29", description: "Unspecified psychosis not due to a substance or known physiological condition" },
  { code: "F52.9", description: "Unspecified sexual dysfunction not due to a substance or known physiological condition" },
  { code: "F52.5", description: "Vaginismus not due to a substance or known physiological condition" },
  { code: "F01.51", description: "Vascular dementia with behavioral disturbance" },
  { code: "F01.50", description: "Vascular dementia without behavioral disturbance" },
  { code: "F65.3", description: "Voyeurism" },
];

const BY_CODE = new Map(ICD10_CODES.map((c) => [c.code, c]));

export function findIcd10ByCode(code: string): Icd10Code | undefined {
  return BY_CODE.get(code);
}

/**
 * Case-insensitive prefix-then-substring search across description and code.
 * Returns up to `limit` matches. Prefix matches in description rank highest,
 * then prefix matches in code, then substring matches.
 */
export function searchIcd10(query: string, limit = 12): Icd10Code[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const descPrefix: Icd10Code[] = [];
  const codePrefix: Icd10Code[] = [];
  const substring: Icd10Code[] = [];
  for (const entry of ICD10_CODES) {
    const d = entry.description.toLowerCase();
    const c = entry.code.toLowerCase();
    if (d.startsWith(q)) descPrefix.push(entry);
    else if (c.startsWith(q)) codePrefix.push(entry);
    else if (d.includes(q) || c.includes(q)) substring.push(entry);
    if (descPrefix.length + codePrefix.length + substring.length >= limit * 3) break;
  }
  return [...descPrefix, ...codePrefix, ...substring].slice(0, limit);
}
